### ISSUE TITLE
Weekly Airdrop Task Time Sensitive

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/token-airdrop-x2e#1]
![Image](https://github.com/MXCzkEVM/token-airdrop-x2e/assets/9674168/66ae3dd3-05b2-44ef-a153-faec9088a382)

https://docs.google.com/spreadsheets/d/1sq2kkg9pwMfkCffQq08-i8fcvjmhe43VhsRI_uIkEgQ/edit#gid=0

![Image](https://github.com/MXCzkEVM/token-airdrop-x2e/assets/9674168/24128e3d-2d8f-401d-86c3-285ed1146382)

**Comment by hairyf** [comment]
- [x] Bridge 2500 MXC from Erc-20 to Zkevm (Tested)
- [x] Make 1 swap on swap.mxc.com (Tested)
- [x] Swap 1000 MXC for $Sensor (Tested)
- [x] Swap 5000 MXC for XSD (Tested)
- [x] Create NFT collection (Tested)
- [x] mint 1 inscription (Tested)
- [x] Mint Hexagon in the USA
- [x] Mint a Hexagon in France
- [x] create your own token on https://discodistro.vercel.app/
- [x] Acquire MNS with NEO name in it
- [x] Hold more than 1000 $CRAB (for the next 30 days?)
- [x] Mint a NEO Miner (probaly duration should be 2-3 weeks, cause shipping and etc)

**Comment by hairyf** [comment]
Add tasks in https://github.com/MXCzkEVM/airdrop-tasks/blob/main/tasks.json, only support Mainnet.

All weekly task numbers:

- week-01: Bridge 2500 MXC from Erc-20 to Zkevm
- week-02: Make 1 swap on swap.mxc.com
- week-03: Swap 1000 MXC for $Sensor
- week-04: Swap 5000 MXC for XSD
- week-05: Mint 1 inscription
- week-06: Create NFT collection
- week-07: Mint Hexagon in USA
- week-08: Mint Hexagon in France
- week-09: Create your own token on https://discodistro.vercel.app/
- week-10: Mint a NEO Miner
- week-11: Hold more than 1000 $CRAB (30 days)
- week-12: Acquire MNS with NEO name in it

Select the corresponding number in tasks.json to add the program that executes tasks daily. Once a number is added, it cannot be added again. The tasks in the JSON will be added as a new round of tasks every Monday.

Note that added tasks cannot be deleted. Even if a task is removed from the JSON, you can contact the developers for deletion.

**Comment by SanghamitraBhowmick1993** [comment]
@sheenhx Would you please help with some guidance on how we can effectively test this, especially considering its time sensitivity? Do we need to test all tasks listed in the airdrop in Geneva and verify if they go through? Also, how can we replicate the 7-day interval?

**Comment by SanghamitraBhowmick1993** [comment]
@hairyf i checked with Sheen, and he asked me to get some inputs from you. 
1. Do i need to test anything as part of this ticket?
2. If yes, how can i test it? 
3. Please correct my understanding - does someone need to add the tasks number manually every Monday in the json file?
4. I opened the URL, for airdrop dapp (https://airdrop.moonchain.com/address/0x0795D90c6d60F7c77041862E9aE5059B4d5e0d7A), but I am unable to see "Bonus Points Achieved" and "Active Bonus tasks"

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993 Now you can try again

**Comment by hairyf** [comment]
Added some support for testing. If necessary, please add `testnet: true` in JSON, 

```json
[
  {
    "task": "week-01",
    "name": "Geneva Bridge 2500 MXC from Erc-20 to Zkevm",
    "zks": 1000,
    "testnet": true
  }
]
```

> On display, please differentiate with titles

New Testnet support:

- week-01: Bridge 2500 MXC from Erc-20 to Zkevm
- week-02: Make 1 swap on swap.mxc.com
- week-03: Swap 1000 MXC for $Sensor
- week-04: Swap 5000 MXC for XSD
- week-05: Mint 1 inscription
- week-06: Create NFT collection
- week-07: Mint Hexagon in USA
- week-08: Mint Hexagon in France
- week-10: Mint a NEO Miner
- week-12: Acquire MNS with NEO name in it

**Comment by SanghamitraBhowmick1993** [comment]
I've made the recommended updates to the JSON file as per the suggestion. However, I've noticed an issue where I can see "ACTIVE BONUS TASK," but due to this ongoing bug (https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=62982871), I may face limitations in proceeding further. Additionally, I'm unable to locate the label "Bonus Point Achieved." Will this label only become visible once some bonus points are achieved?

`[
  {
    "task": "week-01",
    "name": "Bridge 2500 MXC from Erc-20 to Zkevm",
    "zks": 1000
  },
  {
    "task": "week-01",
    "name": "Geneva Bridge 2500 MXC from Erc-20 to Zkevm",
    "zks": 1000,
    "testnet": true
  }
]`

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993 `Bonus Point Achieved ` was not added, but it has now been added

**Comment by SanghamitraBhowmick1993** [comment]
blocked due to https://github.com/orgs/MXCzkEVM/projects/3?pane=issue&itemId=62982871

**Comment by SanghamitraBhowmick1993** [comment]
looks great working as expected hence closing this issue

https://airdrop.moonchain.com/address/0xcEb9B47485fdd900aE66A0ABD275d72c8518cBDf

![Image](https://github.com/user-attachments/assets/ab36896a-d9c4-4cda-97e1-8ad4ceddcb74)
![Image](https://github.com/user-attachments/assets/096e124d-d782-405c-8eb3-c2017ea4d09e)
![Image](https://github.com/user-attachments/assets/f4f8b948-dcb8-4103-bc5e-564973ae8695)
